sudo: false

language: php

php:
  - 5.2
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1

cache:
  - composer
  - npm

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - npm install -g grunt-cli
  - npm install
  - composer install

script:
  - grunt phpcs
  - phpunit
  - grunt jasmine;

notifications:
  email:
    on_success: never
